In [1]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
con = sqlite3.connect(r"C:\Users\HP\Documents\Freight Project\inventory.db")
tables = pd.read_sql_query("SELECT name FROM sqlite_master where type='table'",con)

tables

              name
0        purchases
1  purchase_prices
2   vendor_invoice
3  begin_inventory
4    end_inventory

In [11]:
vendor_df = pd.read_sql_query("select * from vendor_invoice",con)
vendor_df.head()

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,NaN
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,NaN
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,NaN
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,NaN
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,NaN

In [17]:
vendor_df[['Quantity','Freight','Dollars']].corr()

          Quantity   Freight   Dollars
Quantity  1.000000  0.946550  0.963831
Freight   0.946550  1.000000  0.985141
Dollars   0.963831  0.985141  1.000000

In [20]:
vendor_df['Freight_per_quantity'] = vendor_df['Freight']/vendor_df['Quantity']
vendor_df['Freight_per_quantity'].head()

0    0.578333
1    0.571333
2    0.922000
3    0.290614
4    0.221809
Name: Freight_per_quantity, dtype: float64

In [24]:
low_quantity = vendor_df['Quantity'].quantile(0.25)
low_quantity

np.float64(83.0)

In [ ]:
high_quantity = vendor_df['Quantity'].quantile(0.75)
high_quantity

np.float64(5100.5)

In [ ]:
vendor_df.loc[vendor_df['Quantity']<low_quantity,'Freight_per_quantity'].mean()

0       0.578333
1       0.571333
2       0.922000
5       0.100000
7       0.881667
          ...
5523    0.102778
5526    0.088308
5527    0.048611
5528    0.032000
5537    0.053333
Name: Freight_per_quantity, Length: 1384, dtype: float64